ARDUINO_DIR = /usr/share/arduino

TARGET = arduino_code.pde
BOARD_TAG = uno
ARDUINO_PORT = /dev/ttyACM0
AVRDUDE_ARD_PROGRAMMER = stk500v1

ARDUINO_LIBS = AccelStepper

AVR_TOOLS_PATH = /usr/bin
AVRDUDE_CONF = /etc/avrdude.conf

include /usr/share/arduino/Arduino.mk
